# Generated by Django 4.1.1 on 2022-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="gerens",
            field=models.CharField(
                blank=True,
                choices=[("P", "Photography"), ("F", "Food"), ("A", "Art")],
                max_length=50,
                null=True,
            ),
        ),
    ]
