# Generated by Django 4.1.1 on 2022-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_post_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, upload_to="photo/"),
        ),
    ]
