# Generated by Django 4.1.1 on 2024-04-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_post_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(
                blank=True,
                default="file:///D:/vs%20code/project/social/media/noimg.png",
                null=True,
                upload_to="photo/",
            ),
        ),
    ]
